pytest_failure_tracker/__init__.py,sha256=kUR5RAFc7HCeiqdlX36dZOHkUI5wI6V_43RpEcD8b-0,22
pytest_failure_tracker/plugin.py,sha256=v18TdVRGGTgk4gyYkh5VZPh8PgFG1mXFdHzoZT0rbz4,3103
pytest_failure_tracker-0.1.0.dist-info/METADATA,sha256=kCPvcfjzxzSkAWH5iJdJOrFV0jjCR5jkTWzGRHgSZMc,3411
pytest_failure_tracker-0.1.0.dist-info/WHEEL,sha256=Z4pYXqR_rTB7OWNDYFOm1qRk0RX6GFP2o8LgvP453Hk,91
pytest_failure_tracker-0.1.0.dist-info/entry_points.txt,sha256=t6xhJUacb1IZVZVY_FSkAgtOK76gtWnLK2OwKEe3y8g,52
pytest_failure_tracker-0.1.0.dist-info/top_level.txt,sha256=QM3vmr7t0sH3WjTO5pbzwSwnonzZ0zDGXX7OpxMFk_k,23
pytest_failure_tracker-0.1.0.dist-info/RECORD,,
